@url=http://localhost:3000

### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "username": "eladmin",
    "password": "hola1234"
}

###
@token = {{login.response.body.token}}

### Consultar usuarios
GET {{url}}/usuarios
Authorization: Bearer {{token}}

### Consultar por un usuario
GET {{url}}/usuarios/1

### Consultar por roles de usuario
GET {{url}}/usuarios/3/roles

### Crear usuario
POST {{url}}/usuarios
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "userpro",
    "apellido": "pro",
    "nombre":"usuario",
    "password": "Qwerty25"
}

### Asignar rol a usuario
POST {{url}}/usuarios/3/roles
Content-Type: application/json

{
    "rolId": 1
}

### Quitar rol a usuario
DELETE {{url}}/usuarios/3/roles/5
